In [4]:
import numpy as np

x = np.array([1,2,3], np.int16)

In [4]:
print(x)

print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
print(x[0]); print(x[1]); print(x[2])

1
2
3


In [6]:
print(x[-1]); print(x[3]) # bounds  error

3


IndexError: index 3 is out of bounds for axis 0 with size 3

In [5]:
#2dim array
x = np.array([[1,2,3], [4,5,6]], np.int16)
print(x)

[[1 2 3]
 [4 5 6]]


In [7]:
print(x[0, 0]); print(x[0, 1]); print(x[0, 2]) #upper layer (ROW) of two dim numpy array

1
2
3


In [8]:
print(x[:, 0])# first column 

[1 4]


In [9]:
print(x[:, 1])

[2 5]


In [10]:
print(x[:, 2])

[3 6]


In [11]:
print(x[0, :])

[1 2 3]


In [13]:
print(x[1, :])

[4 5 6]


In [14]:
#3dim array

x = np.array([[[1,2,3], [4,5,6], [7, 8, 9]]],  np.int16)
print(x)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
print(x[0, 0, 0])

1


In [18]:
print(x[0, 1, 1])

5


In [21]:
print(x[0, 2, 2])

9


In [22]:
print(x[:, :, 0])

[[1 4 7]]


In [24]:
print(x[:, 1, :])

[[4 5 6]]
