# Ones and Zeros 

In [2]:
import numpy as np 

x = np.empty([3, 3], np.uint8) # give random aray
print(x)

[[176  49  91]
 [194  17 127]
 [  0   0  48]]


In [3]:
y = np.eye(5, dtype=np.int8, k=1) # Diagonal
print(y)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [4]:
x = np.identity(5, dtype= np.uint)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [5]:
x = np.ones((2, 5, 5), dtype=np.int16)
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [6]:
x = np.zeros((2, 5, 5), dtype=np.int16)
print(x)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [7]:
x = np.full((3, 3, 3), dtype=np.int16, fill_value = 3)
print(x)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


# Matrix Creation Routines

In [11]:
x = np.tri(3, 3, k=0, dtype=np.uint16)
print(x)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [13]:
x = np.tri(5, 5, k=1, dtype=np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
x = np.tri(5, 5, k=-1, dtype=np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [20]:
x = np.ones((5, 5), dtype=np.uint8)
y = np.tril(x, k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [24]:
x = np.ones((5, 5), dtype=np.uint8)
y = np.triu(x, k=0)  
print(y)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


In [26]:
x = np.ones((5, 5), dtype=np.uint8)
y = np.triu(x, k=1)
print(y)

[[0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
