# Ones and Zeros 

In [3]:
import numpy as np 

x = np.empty([3, 3], np.uint8) # give random aray
print(x)

[[ 48 237 158]
 [ 57 179 127]
 [  0   0  80]]


In [7]:
y = np.eye(5, dtype=np.int8, k=1) # Diagonal
print(y)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [9]:
x = np.identity(5, dtype= np.uint)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [13]:
x = np.ones((2, 5, 5), dtype=np.int16)
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [15]:
x = np.zeros((2, 5, 5), dtype=np.int16)
print(x)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [17]:
x = np.full((3, 3, 3), dtype=np.int16, fill_value = 3)
print(x)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
