In [2]:
import numpy as np

In [27]:
x = np.random.randint( low = 0, high = 9, size = 10 )
print(x)

[2 8 3 6 5 7 5 4 1 0]


In [31]:
x = np.random.rand(3, 3)
print(x)

[[0.77250126 0.20794592 0.6801029 ]
 [0.63181779 0.25392821 0.13746867]
 [0.02063609 0.32654585 0.17017103]]


In [34]:
x = np.random.rand(3, 3, 3)
print(x)

[[[0.83592123 0.03933277 0.93757072]
  [0.35075004 0.78828192 0.7451579 ]
  [0.8592747  0.03141973 0.42061357]]

 [[0.60233758 0.63601622 0.10772004]
  [0.32156218 0.30767268 0.59066566]
  [0.00706494 0.37782507 0.91632212]]

 [[0.96389384 0.6717538  0.98662134]
  [0.52997307 0.43343394 0.97591738]
  [0.63851535 0.51657831 0.10291175]]]


In [37]:
x = np.random.rand(2, 2, 2, 2, 2)
print(x)

[[[[[0.51321758 0.40033218]
    [0.49060533 0.09418687]]

   [[0.86193967 0.10230993]
    [0.01554703 0.16938641]]]


  [[[0.03473921 0.58388169]
    [0.57920118 0.16359348]]

   [[0.87590827 0.71369479]
    [0.1380269  0.46483774]]]]



 [[[[0.69032388 0.63247566]
    [0.25639373 0.66041087]]

   [[0.51624013 0.33946233]
    [0.73937933 0.56549081]]]


  [[[0.76391727 0.83397219]
    [0.155781   0.65222101]]

   [[0.14848184 0.16027339]
    [0.37943349 0.08090765]]]]]
