# Array Manipulation Routines

In [1]:
import numpy as np
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [4]:
y = x.reshape((3, 2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [7]:
x = np.array([[0, 1, 2], [3, 4, 5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [12]:
y = np.reshape(x , 6)
print(y)

[0 1 2 3 4 5]


In [13]:
print(x)

[[0 1 2]
 [3 4 5]]


In [15]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [16]:
print(x)

[[0 1 2]
 [3 4 5]]


In [19]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [20]:
y = x.flatten('C')
print(y)

[0 1 2 3 4 5]


In [21]:
y = x.flatten('F')
print(y)

[0 3 1 4 2 5]


In [22]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5 , 6], dtype = np.uint8)

print(x.dtype)

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]
