# Array Manipulation Routines

In [7]:
import numpy as np
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [8]:
y = x.reshape((3, 2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [9]:
x = np.array([[0, 1, 2], [3, 4, 5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [10]:
y = np.reshape(x , 6)
print(y)

[0 1 2 3 4 5]


In [11]:
print(x)

[[0 1 2]
 [3 4 5]]


In [12]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [13]:
print(x)

[[0 1 2]
 [3 4 5]]


In [14]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [15]:
y = x.flatten('C')
print(y)

[0 1 2 3 4 5]


In [16]:
y = x.flatten('F')
print(y)

[0 3 1 4 2 5]


In [18]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5 , 6], dtype = np.uint8)

print(x.dtype)

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [20]:
z = np.stack((x, y))
print(x)

[1 2 3]


In [27]:
z = np.stack((x, y), axis = 0)
print(z)

[[1 2 3]
 [4 5 6]]


In [28]:
z = np.stack((x, y), axis = -1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
z = np.stack((x, y), axis = 1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [26]:
z = np.dstack((x, y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [30]:
z = np.stack((x, y), axis = -1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
print(z.shape)

(3, 2)


In [33]:
z = np.hstack((x, y))
print(z)

[1 2 3 4 5 6]


In [34]:
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [35]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [37]:
a, b, c = np.split(x, 3)
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [38]:
x = np.random.rand(4, 4, 4)
print(x)

[[[0.11725438 0.26029089 0.65428219 0.9089001 ]
  [0.40823838 0.69764766 0.26389687 0.67372486]
  [0.65372432 0.02072366 0.51274151 0.63252549]
  [0.17841473 0.70968969 0.77212603 0.16508572]]

 [[0.26876834 0.37662725 0.22796468 0.95519362]
  [0.19253762 0.78628132 0.6773324  0.82011374]
  [0.858922   0.48738009 0.17506944 0.23180879]
  [0.53345859 0.76365733 0.02262287 0.7037336 ]]

 [[0.91507863 0.54014035 0.73162109 0.2508354 ]
  [0.4233048  0.07995287 0.58637087 0.07373773]
  [0.36056569 0.22140659 0.90888542 0.42910244]
  [0.16700043 0.81417469 0.45600404 0.78627084]]

 [[0.45617148 0.88539758 0.46453519 0.23573944]
  [0.20859856 0.24148752 0.92052159 0.89974893]
  [0.3732446  0.68933972 0.25029976 0.23328349]
  [0.0330443  0.19215522 0.10869702 0.66119546]]]


In [39]:
y, z = np.split(x, 2)
print(y, z)

[[[0.11725438 0.26029089 0.65428219 0.9089001 ]
  [0.40823838 0.69764766 0.26389687 0.67372486]
  [0.65372432 0.02072366 0.51274151 0.63252549]
  [0.17841473 0.70968969 0.77212603 0.16508572]]

 [[0.26876834 0.37662725 0.22796468 0.95519362]
  [0.19253762 0.78628132 0.6773324  0.82011374]
  [0.858922   0.48738009 0.17506944 0.23180879]
  [0.53345859 0.76365733 0.02262287 0.7037336 ]]] [[[0.91507863 0.54014035 0.73162109 0.2508354 ]
  [0.4233048  0.07995287 0.58637087 0.07373773]
  [0.36056569 0.22140659 0.90888542 0.42910244]
  [0.16700043 0.81417469 0.45600404 0.78627084]]

 [[0.45617148 0.88539758 0.46453519 0.23573944]
  [0.20859856 0.24148752 0.92052159 0.89974893]
  [0.3732446  0.68933972 0.25029976 0.23328349]
  [0.0330443  0.19215522 0.10869702 0.66119546]]]


In [40]:
y, z = np.dsplit(x, 2)
print(y, z)

[[[0.11725438 0.26029089]
  [0.40823838 0.69764766]
  [0.65372432 0.02072366]
  [0.17841473 0.70968969]]

 [[0.26876834 0.37662725]
  [0.19253762 0.78628132]
  [0.858922   0.48738009]
  [0.53345859 0.76365733]]

 [[0.91507863 0.54014035]
  [0.4233048  0.07995287]
  [0.36056569 0.22140659]
  [0.16700043 0.81417469]]

 [[0.45617148 0.88539758]
  [0.20859856 0.24148752]
  [0.3732446  0.68933972]
  [0.0330443  0.19215522]]] [[[0.65428219 0.9089001 ]
  [0.26389687 0.67372486]
  [0.51274151 0.63252549]
  [0.77212603 0.16508572]]

 [[0.22796468 0.95519362]
  [0.6773324  0.82011374]
  [0.17506944 0.23180879]
  [0.02262287 0.7037336 ]]

 [[0.73162109 0.2508354 ]
  [0.58637087 0.07373773]
  [0.90888542 0.42910244]
  [0.45600404 0.78627084]]

 [[0.46453519 0.23573944]
  [0.92052159 0.89974893]
  [0.25029976 0.23328349]
  [0.10869702 0.66119546]]]


In [41]:
y, z = np.hsplit(x, 2)
print(y, z)

[[[0.11725438 0.26029089 0.65428219 0.9089001 ]
  [0.40823838 0.69764766 0.26389687 0.67372486]]

 [[0.26876834 0.37662725 0.22796468 0.95519362]
  [0.19253762 0.78628132 0.6773324  0.82011374]]

 [[0.91507863 0.54014035 0.73162109 0.2508354 ]
  [0.4233048  0.07995287 0.58637087 0.07373773]]

 [[0.45617148 0.88539758 0.46453519 0.23573944]
  [0.20859856 0.24148752 0.92052159 0.89974893]]] [[[0.65372432 0.02072366 0.51274151 0.63252549]
  [0.17841473 0.70968969 0.77212603 0.16508572]]

 [[0.858922   0.48738009 0.17506944 0.23180879]
  [0.53345859 0.76365733 0.02262287 0.7037336 ]]

 [[0.36056569 0.22140659 0.90888542 0.42910244]
  [0.16700043 0.81417469 0.45600404 0.78627084]]

 [[0.3732446  0.68933972 0.25029976 0.23328349]
  [0.0330443  0.19215522 0.10869702 0.66119546]]]


In [42]:
y, z = np.vsplit(x, 2)
print(y, z)

[[[0.11725438 0.26029089 0.65428219 0.9089001 ]
  [0.40823838 0.69764766 0.26389687 0.67372486]
  [0.65372432 0.02072366 0.51274151 0.63252549]
  [0.17841473 0.70968969 0.77212603 0.16508572]]

 [[0.26876834 0.37662725 0.22796468 0.95519362]
  [0.19253762 0.78628132 0.6773324  0.82011374]
  [0.858922   0.48738009 0.17506944 0.23180879]
  [0.53345859 0.76365733 0.02262287 0.7037336 ]]] [[[0.91507863 0.54014035 0.73162109 0.2508354 ]
  [0.4233048  0.07995287 0.58637087 0.07373773]
  [0.36056569 0.22140659 0.90888542 0.42910244]
  [0.16700043 0.81417469 0.45600404 0.78627084]]

 [[0.45617148 0.88539758 0.46453519 0.23573944]
  [0.20859856 0.24148752 0.92052159 0.89974893]
  [0.3732446  0.68933972 0.25029976 0.23328349]
  [0.0330443  0.19215522 0.10869702 0.66119546]]]


In [43]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [45]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [46]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [48]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [50]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [52]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [53]:
y = np.roll(x, 8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [54]:
y = np.rot90(x)
print(y)

[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
