# NumPy Array

In [1]:
my_list = [1,2,3]

In [6]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5)

array([0.92905753, 0.89628147, 0.52970126, 0.02247191, 0.16834227])

In [30]:
np.random.rand(5,5)

array([[0.47155237, 0.71095702, 0.81803459, 0.56707705, 0.87389155],
       [0.77984346, 0.99547931, 0.67309272, 0.87236437, 0.63638779],
       [0.10509327, 0.75430161, 0.00651503, 0.78164073, 0.34638217],
       [0.26562937, 0.77679949, 0.86653501, 0.14438199, 0.87356514],
       [0.20882491, 0.80939347, 0.59588271, 0.50057575, 0.47655621]])

In [32]:
np.random.randn(2)

array([ 0.85893099, -0.55785987])

In [33]:
np.random.randn(4,4)

array([[ 1.28759725,  1.23391581, -0.12395567,  0.68600124],
       [-0.94078574,  0.56153312, -1.23064574,  0.63777543],
       [ 0.98786463,  1.62275527, -0.05851367,  1.7460914 ],
       [ 0.54625234,  0.32068387,  0.14730977, -0.3900704 ]])

In [35]:
np.random.randint(1,100,10)

array([73, 81, 47, 50, 84, 53, 91,  1, 78, 61])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([ 7, 17, 12,  5,  2, 23, 24, 49, 13,  7])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ranarr.max()

49

In [43]:
ranarr.min()

2

In [44]:
ranarr

array([ 7, 17, 12,  5,  2, 23, 24, 49, 13,  7])

In [45]:
ranarr.argmax()

7

In [46]:
ranarr.argmin()

4

In [47]:
arr.shape

(25,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr.shape

(5, 5)

In [50]:
arr.dtype

dtype('int64')

# Data-Science --date 12/9/2k19 --network localhost
# AAKASH-PADHIYAR  --contact --email iampythonistas@gmail.com --anotherGITHUB www.github.com/8140171224
# IKNOW --language python javascript dart c-language  --website HTML CSS BOOTSTRAP  --frameworks DJANGO FLUTTER FLASK & more