In [3]:
import numpy as np
x = np.array([0, 1, 0, 1], np.int8)
y = np.array([0, 0, 1, 1], np.uint8)

In [4]:
print(np.bitwise_and(x, y))

[0 0 0 1]


In [5]:
print(np.bitwise_or(x, y))

[0 1 1 1]


In [6]:
print(np.bitwise_xor(x, y))

[0 1 1 0]


In [10]:
print(np.bitwise_not(x))

[-1 -2 -1 -2]
